[package]
name = "devinfo"
version = "0.1.0"
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
edition = "2018"


[dependencies]
snafu = "0.6"
udev = "0.4"
url = "2.1"
uuid = { version = "0.7", features = ["v4"] }



