[package]
name = "rest"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rest"
path = "./service/src/main.rs"

[lib]
name = "rest_client"
path = "./src/lib.rs"

[dependencies]
rustls = "0.18"
actix-web = { version = "3.2.0", features = ["rustls"] }
mbus_api = { path = "../mbus-api" }
async-trait = "0.1.41"
serde_json = "1.0"
structopt = "0.3.15"
futures = "0.3.6"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
strum = "0.19"
strum_macros = "0.19"
anyhow = "1.0.32"
snafu = "0.6"

[dev-dependencies]
composer = { path = "../composer" }
rpc = { path = "../rpc" }
tokio = { version = "0.2", features = ["full"] }
actix-rt = "1.1.1"

[dependencies.serde]
features = ["derive"]
version = "1.0"