name: "Lint and style Checks"
on:
  pull_request:
  push:
    branches:
      - msn_updates
jobs:
  Clippy:
    name: Clippy
    runs-on: self-hosted
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - run: ls -Rta /github/home/
      - run: env
      - run: rustup -v || true
      - run: rustc || true
      - run: cargo || true
      - run: rustup toolchain install nightly-2020-06-10
      - run: rustup default nightly-2020-06-10
      - uses: actions/checkout@master
      - uses: actions-rs/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets -- -D warnings
  Semistandard:
    name: SemiStandard
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@master
      - run: git ls-files | grep '\.js$' | xargs -r ./scripts/js-check.sh
        shell: bash
