name: "Lint and style Checks"
on:
  pull_request:
jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:gila
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          components: clippy
      - uses: actions-rs/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets -- -D warnings
  Semistandard:
    name: SemiStandard
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:gila
    steps:
      - uses: actions/checkout@master
      - run: git ls-files | grep '\.js$' | xargs -r ./scripts/js-check.sh
        shell: bash
